#!/usr/bin/env bash

# Removes stuff generated by Qt, CMake, ninja and clangd

exec_in_dir() {
    cd $1 && echo "cleaning $1"
    rm -f *.exe *.a *.dll CMakeCache.txt cmake_install.cmake \
        build.ninja .ninja_deps .ninja_log compile_commands.json *.user

    rm -rf CMakeFiles .qt *_autogen build .cache
}

exec_in_dir .
exec_in_dir lib/REST
