services:
  database:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    env_file:
      - path: ./env/db.env
    secrets:
      - db_root_password

  app:
    image: node:21
    depends_on:
      - database
    environment:
      PORT: ${APP_PORT}
    env_file:
      - path: ./env/app.env
    secrets:
      - app_secret
      - app_db_password
    restart: unless-stopped
    command: npm start
    working_dir: /app
    volumes:
      - ../backend:/app
      - ../backend/log:/log

  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '10.0.0.1:81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  app_secret:
    file: ./secrets/app_secret.txt
  app_db_password:
    file: ./secrets/db_root_password.txt
