DROP TABLE IF EXISTS `Account`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Friend`;
DROP TABLE IF EXISTS `Administrator`;
DROP TABLE IF EXISTS `Transaction`;
DROP TABLE IF EXISTS `Card_Account`;
DROP TABLE IF EXISTS `Card`;
