-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 14:24:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `type` ENUM('debit', 'credit') NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `limit` DECIMAL(10,2) NOT NULL DEFAULT 0,
  UNIQUE INDEX `accountId_UNIQUE` (`idAccount` ASC) VISIBLE,
  PRIMARY KEY (`idAccount`),
  INDEX `fk_Account_User` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Card` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `pinHash` VARCHAR(255) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  `frozen` TINYINT NOT NULL DEFAULT 0,
  `failedPinAttempts` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idCard`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE,
  INDEX `fk_Card_User1_idx` (`User_id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `fk_Card_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `Card_id` INT NULL DEFAULT NULL,
  `Account_id` INT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `balanceChange` DECIMAL(10,2) NOT NULL,
  `transactionType` ENUM('withdraw', 'deposit') NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `fk_Transaction_Card_idx` (`Card_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`idTransaction` ASC) VISIBLE,
  INDEX `fk_Transaction_Account_idx` (`Account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_Card`
    FOREIGN KEY (`Card_id`)
    REFERENCES `mydb`.`Card` (`idCard`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Transaction_Account`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friend` (
  `idFriend` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Account_id` INT NOT NULL,
  INDEX `fk_Friend_Account_idx` (`Account_id` ASC) VISIBLE,
  PRIMARY KEY (`idFriend`),
  INDEX `fk_Friend_User` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Friend_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friend_Account`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Card_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Card_Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Card_Account` (
  `idCard_Account` INT NOT NULL AUTO_INCREMENT,
  `Card_id` INT NOT NULL,
  `Account_id` INT NOT NULL,
  PRIMARY KEY (`idCard_Account`),
  INDEX `fk_Card_Account_Card1_idx` (`Card_id` ASC) VISIBLE,
  INDEX `fk_Card_Account_Account1_idx` (`Account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_Account_Card1`
    FOREIGN KEY (`Card_id`)
    REFERENCES `mydb`.`Card` (`idCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Account_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `idAdministrator` INT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAdministrator`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
